version: '3.8'

networks:
  backend:
  frontend:

services:
  nginx:
    image: nginx:latest
    container_name: webserver-nginx
    volumes:
      - /home/monxas/appdata/nginx/conf.d:/etc/nginx/conf.d
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    ports:
      - "80:80"
    networks:
      - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: media-radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/monxas/appdata/radarr:/config
      - /mnt/nfs_media:/data
    ports:
      - "7878:7878"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: media-sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/monxas/appdata/sonarr:/config
      - /mnt/nfs_media:/data
    ports:
      - "8989:8989"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: media-lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/monxas/appdata/lidarr:/config
      - /mnt/nfs_media:/data
    ports:
      - "8686:8686"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: media-bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/monxas/appdata/bazarr:/config
      - /mnt/nfs_media/movies:/movies
      - /mnt/nfs_media/tvshows:/tv
    ports:
      - "6767:6767"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: media-readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/monxas/appdata/readarr:/config
      - /mnt/nfs_media:/data
    ports:
      - "8787:8787"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  sonarr_monitor:
    image: monxas/putio-torrent-monitor:latest
    container_name: monitor-sonarr
    environment:
      - PARENT_ID=1244743180
      - PUTIO_OAUTH_TOKEN=I5RCKVANJ6HJME4TPLKR
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /mnt/nfs_media/torrents/sonarr:/torrents
    networks:
      - backend
    restart: unless-stopped

  radarr_monitor:
    image: monxas/putio-torrent-monitor:latest
    container_name: monitor-radarr
    environment:
      - PARENT_ID=1244692884
      - PUTIO_OAUTH_TOKEN=I5RCKVANJ6HJME4TPLKR
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /mnt/nfs_media/torrents/radarr:/torrents
    networks:
      - backend
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: media-jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/monxas/appdata/jellyfin:/config
      - /mnt/nfs_media:/data
    ports:
      - "8096:8096"
      - "8920:8920"
    networks:
      - frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  jellystat-db:
    image: postgres:15.2
    container_name: db-jellystat
    environment:
      POSTGRES_DB: 'jfstat'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'mypassword'
      TZ: 'Europe/Madrid'
    volumes:
      - /home/monxas/appdata/jellystat-db:/var/lib/postgresql/data
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: media-jellystat
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'mypassword'
      POSTGRES_IP: 'db-jellystat'
      POSTGRES_PORT: '5432'
      JWT_SECRET: 'my-secret-jwt-key'
      TZ: 'Europe/Madrid'
      PUID: '1000'
      PGID: '1000'
    ports:
      - "3100:3000"
    volumes:
      - /home/monxas/appdata/jellystat-backup:/app/backend/backup-data
    depends_on:
      - db-jellystat
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: media-jellyseerr
    environment:
      - LOG_LEVEL=debug
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/monxas/appdata/jellyseerr:/app/config
    ports:
      - "5055:5055"
    networks:
      - frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: media-prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/monxas/appdata/prowlarr:/config
    ports:
      - "9696:9696"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: torrent-qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8080
      - DOCKER_MODS=marzzzello/linuxserver-io-mod-qbit-matui
    volumes:
      - /home/monxas/appdata/qbittorrent:/config
      - /mnt/nfs_media:/data
    ports:
      - "8080:8080"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  dozzle:
    image: amir20/dozzle:latest
    container_name: monitoring-dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9999:8080"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: update-watchtower
    environment:
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - WATCHTOWER_CLEANUP=true
      - TZ=Europe/Madrid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: dashboard-heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/monxas/appdata/heimdall:/config
    ports:
      - "8084:80"
    networks:
      - frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  whatsupdocker:
    image: fmartinou/whats-up-docker
    container_name: monitoring-wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WUD_REGISTRY_LSCR_TOKEN=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
    ports:
      - "3000:3000"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  stirling-pdf:
    image: frooodle/s-pdf
    container_name: tool-stirling-pdf
    ports:
      - "9090:8080"
    volumes:
      - /home/monxas/appdata/pdf/trainingData:/usr/share/tesseract-ocr/4.00/tessdata 
      - /home/monxas/appdata/pdf/config:/configs
    environment:
      APP_LOCALE: es_ES
      APP_HOME_NAME: Stirling PDF
      APP_HOME_DESCRIPTION: Your locally hosted one-stop-shop for all your PDF needs.
      APP_NAVBAR_NAME: Stirling PDF
      APP_ROOT_PATH: /
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  changedetection:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: monitoring-changedetection
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBDRIVER_URL=http://selenium:4444/wd/hub
    volumes:
      - /home/monxas/appdata/changedetection:/config
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - selenium
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: tool-selenium
    environment:
      - DEBUG=browserless:*
      - MAX_CONCURRENT_SESSIONS=10
      - CONNECTION_TIMEOUT=60000
      - MAX_QUEUE_LENGTH=20
      - PREBOOT_CHROME=true
      - DEMO_MODE=false
      - ENABLE_DEBUGGER=false
      - TOKEN=alfagann
      - WORKSPACE_DELETE_EXPIRED=true
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2g
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  snapdrop:
    image: lscr.io/linuxserver/snapdrop:latest
    container_name: tool-snapdrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/monxas/appdata/snapdrop:/config
    ports:
      - "8085:80"
    networks:
      - frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  portainer:
    image: portainer/portainer-ce:latest
    container_name: management-portainer
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/monxas/appdata/portainer:/data
    networks:
      - frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  ydl_api_ng:
    image: totonyus/ydl_api_ng
    container_name: api-ydl
    restart: unless-stopped
    depends_on:
      - ydl_api_ng_redis
    ports:
      - "5011:80"
    volumes:
      - /home/monxas/appdata/ydl_api_ng/params:/app/params
      - /home/monxas/appdata/ydl_api_ng/logs:/app/logs
      - /mnt/nfs_media/nopor:/app/downloads
      - /home/monxas/appdata/ydl_api_ng/data:/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - UID=1000
      - GID=1000
      - NB_WORKERS=5
      - LOG_LEVEL=error
      - DISABLE_REDIS=false
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  ydl_api_ng_redis:
    image: redis
    container_name: db-ydl-api-ng
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  stash:
    image: stashapp/stash:latest
    container_name: tool-stash
    restart: unless-stopped
    ports:
      - "9990:9999"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PORT=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/monxas/appdata/stash/config:/root/.stash
      - /mnt/nfs_media/nopor:/data
      - /home/monxas/appdata/stash/metadata:/metadata
      - /home/monxas/appdata/stash/cache:/cache
      - /home/monxas/appdata/stash/blobs:/blobs
      - /home/monxas/appdata/stash/generated:/generated
    networks:
      - backend

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: tool-calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - /home/monxas/appdata/calibre-web:/config
      - /mnt/nfs_media/calibre-library:/libros
    ports:
      - "8083:8083"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped

  glance:
    image: glanceapp/glance
    container_name: tool-glance
    ports:
      - "6080:8080"
    volumes:
      - /home/monxas/appdata/glance/glance.yml:/app/glance.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: dev-code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - PASSWORD=alfagann
      - PROXY_DOMAIN=dev.monxas.casa
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - ./appdata/vscode:/config
    ports:
      - "8443:8443"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped
